[SNOWFLAKE]
# When running locally, fill all of these (USER/PASSWORD/ACCOUNT are not required inside Streamlit in Snowflake):
USER = "your_user"                  # omit when running in Streamlit in Snowflake
PASSWORD = "your_password"          # omit when running in Streamlit in Snowflake
ACCOUNT = "your_account"            # e.g. xy12345.us-east-1 (omit in Streamlit in Snowflake)
WAREHOUSE = "COMPUTE_WH"            # optional in Snowsight; app will use active warehouse if available

# Optional context overrides (work both locally and in Snowsight)
DATABASE = "FSI_DEMOS"
SCHEMA = "WEALTH_360"
ROLE = "ACCOUNTADMIN"
